### ISSUE TITLE
안녕하세요 영권님

### ISSUE THREAD

**Issue by juwon8891** [youngkwon02/youngkwon.site-server#73]
안녕하세요 포트폴리오 템플릿으로 잘 만드신 것같아서 혹시 괜찮으시면 가져가서 사용해도 가능할까요?

**Comment by youngkwon02** [comment]
네 알겠습니다~🙂

**Comment by juwon8891** [comment]
감사합니다!! 혹시 죄송하지만 secret.json에 넣어야 하는게 어떤걸까요?
<img width="557" alt="image" src="https://user-images.githubusercontent.com/74857614/210267595-e523935d-701f-4478-9c1f-a618393b1a90.png">
